name: gimmemotifs
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - configparser
  - diskcache
  - feather-format
  - genomepy >=0.8.3
  - jinja2
  - logomaker
  - matplotlib-base >=3.1.2
  - ncurses
  - numpy
  - pandas >=1.0.3
  - pillow
  - pyarrow >=0.16.0
  - pybedtools
  - python >=3
  - python-xxhash
  - pyyaml >=3.10
  - qnorm >= 0.4.0
  - represent
  - scikit-learn >=0.18
  - scipy >=1.3.0
  - seaborn
  - statsmodels
  - tqdm >=4.27.0
  - xdg
  - xgboost >=0.71
  - sphinx_bootstrap_theme
  - numpydoc
